### ISSUE TITLE
Collections search and Map search - cannot filter results by taxon or collection

### ISSUE THREAD

**Issue by mandrewj** [BioCache/NEON-Biorepository#10]
When performing a map search, e.g. for all plants, even if you de-select specific collections (e.g. deselect SEInet records so only NEON records are displayed) - the final map display and record set returned includes specimens from the excluded collections.

**Comment by arbolitoloco** [comment]
If you unselect everything, and then select the desired ones (non-SEINET/SCAN), then search performs as expected.

Form submission issue.

**Comment by arbolitoloco** [comment]
This turned out to be a taxononomic thesaurus issue, caused by early harvesting of homonyms shared between Animalia and Plantae. As a result, animal genera had been accidentally parsed to the Plantae tree. A search using SCAN specimens and parameter scientific name = "Plantae" used to yield a couple hundred results. To fix this issue, the following workflow was established:

1. Query SCAN database for "correct" genera authors and taxonomic placement, including all higher taxa (more inclusive than genera, because NEON only had Insecta trees up to family),
2. Export csv with fields necessary for batch uploading taxonomic file via interface,
3. Bach upload taxonomic file via interface,
4. Manually reassociate SCAN species that were in Plantae with their appropriate Animalia genera using `taxonomydisplay.php`,
5. Made sure animal genera had authors associated with them,
6. Manually edited occurrences determined to genus level to reflect their correct determination using `batchdeterminations.php`.
